---
title: "Programming Assignmet Week2"
author: "Koffi"
date: "2020/9/6"
output: pdf_document
---

## Programming Assigment 
# Part 1
```{r setup, include=TRUE}
source("pollutantmean.R")
print(R.version.string)
```


```{r}
mp = file.path("..","Data","specdata")
pollutantmean(mp, "nitrate")
```

```{r}
#question 1
pollutantmean(mp, "sulfate", 1:10)
```
```{r}
pollutantmean(mp, "nitrate", 70:72)
```
```{r}
pollutantmean(mp, "nitrate")
```
# Part 2
```{r}
source("complete.R")
```


```{r}
mp = file.path("..","Data","specdata")
complete(mp, 1)
```
```{r}
complete(mp, c(2, 4, 8, 10, 12))
```
```{r}
complete(mp, 30:25)
```


```{r}
complete(mp, 3)
```
```{r}
cc<-complete(mp,  54)
print(cc$nobs)
```


```{r}
RNGversion("3.5.1")  
set.seed(42)
cc <- complete(mp, 332:1)
use <- sample(332, 10)
print(cc[use, "nobs"])
```


```{r}
cc<-complete(mp,  c(6, 10, 20, 34, 100, 200, 310))
print(cc$nobs)
```


```{r}
```

# Part 3
```{r}
source("corr.R")
```

```{r}
mp = file.path("..","Data","specdata")
cr <- corr(mp, 150)
head(cr)
```
```{r}
summary(cr)
```

```{r}
cr <- corr(mp, 400)
head(cr)
```

```{r}
summary(cr)
```

```{r}
cr <- corr(mp, 5000)
summary(cr)
```

```{r}
length(cr)
```

```{r}
cr <- corr(mp)
summary(cr)
```

```{r}
length(cr)
```
```{r}
cr <- corr(mp)                
cr <- sort(cr)   
RNGversion("3.5.1")
set.seed(868)                
out <- round(cr[sample(length(cr), 5)], 4)
print(out)
```
```{r}
cr <- corr(mp, 129)                
cr <- sort(cr)                
n <- length(cr)    
RNGversion("3.5.1")
set.seed(197)                
out <- c(n, round(cr[sample(n, 5)], 4))
print(out)
```
```{r}
cr <- corr(mp, 2000)                
n <- length(cr)                
cr <- corr(mp, 1000)                
cr <- sort(cr)
print(c(n, round(cr, 4)))
```

